# Generated by Django 3.1.14 on 2023-10-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(verbose_name='Дата и время появления')),
                ('disappeared_at', models.DateTimeField(verbose_name='Дата и время исчезновения')),
                ('level', models.IntegerField(blank=True, default=0, null=True, verbose_name='Уровень')),
                ('health', models.IntegerField(blank=True, default=0, null=True, verbose_name='Здоровье')),
                ('strength', models.IntegerField(blank=True, default=0, null=True, verbose_name='Атака')),
                ('defence', models.IntegerField(blank=True, default=0, null=True, verbose_name='Защита')),
                ('stamina', models.IntegerField(blank=True, default=0, null=True, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
        ),
    ]
